version: "3.5"
services:
  db:
    image: mariadb:10
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  app:
    build: .
    entrypoint: bin/docker-entrypoint.sh
    command: bin/rails s -p ${PORT:-3000} -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle/
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mysql2://root@db/pfadismn_development
      RAILS_ENV: development
      APP_HOST: "pfadismn.localhost:3000"
      MAILER_URL: "smtp://mail"
    depends_on:
      - db
      - mail

  mail:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"

volumes:
  bundle:
  node_modules:
