default: &default
  adapter:  mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: pfadismn_development

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: pfadismn_test
  pool:     5
  username:
  password: 
