# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de87272a5bcaee89792de14374024ec9fe74688dfe147f3f3ae84db03b3500085111ec5ddbff658a474d89d0e2268ebd6a2396c5642561bc36986e7f5ee89e26

test:
  secret_key_base: 47bb919144fd2c6b7f3cea953f79486fed3936bb7805e80c2da9f61780d777482d78db95b2545c483a11ebd0ece2df27cc98fb0e18d2f1b81c23d4601453e81c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
